// Additional recipes — 32 new entries to bring total from 19 to 51
// Each replaces a specific category of processed food with a healthier homemade version

const additionalRecipes = [
  // ── BEVERAGES ──
  {
    name: 'Fruit-Infused Sparkling Water',
    description: 'Refreshing fizzy drink with real fruit — replaces soda and flavored sparkling water',
    replaces_category: 'Soda & Flavored Water',
    replaces_products: [],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    total_time_minutes: 65,
    servings: 4,
    difficulty: 'easy',
    estimated_cost: 3.00,
    cost_per_serving: 0.75,
    ingredients: [
      { item: 'Plain sparkling water', amount: '1 liter', notes: 'Any unflavored seltzer' },
      { item: 'Fresh strawberries', amount: '1 cup', notes: 'Sliced, or use any berries' },
      { item: 'Fresh mint leaves', amount: '8-10 leaves', notes: 'Optional' },
      { item: 'Fresh lemon', amount: '1/2', notes: 'Sliced into rounds' },
      { item: 'Honey', amount: '1 tbsp', notes: 'Optional — dissolve in 1 tbsp warm water first' }
    ],
    instructions: [
      'Add sliced fruit and mint to a large pitcher.',
      'Gently muddle a few pieces to release flavor.',
      'Pour sparkling water over the fruit slowly to preserve carbonation.',
      'Stir gently, add honey water if desired.',
      'Let sit in fridge for 1 hour for best flavor (or serve immediately).',
      'Serve over ice. Keeps 24 hours in fridge.'
    ],
    tips: ['Cucumber + lime is another great combo', 'Freeze fruit in ice cube trays for built-in flavor cubes'],
    health_benefits: ['Zero added sugar', 'No artificial sweeteners (aspartame, sucralose)', 'No phosphoric acid', 'No caramel color'],
    vs_store_bought: 'Coca-Cola has 39g sugar plus phosphoric acid and caramel color (4-MEI). Diet versions use aspartame. This has 0g added sugar and real nutrients from fruit.',
    kid_friendly: true,
    allergens: [],
    dietary_tags: ['vegan', 'gluten-free', 'sugar-free', 'no-artificial-sweeteners']
  },
  {
    name: 'Vanilla Oat Milk Coffee Creamer',
    description: 'Rich, creamy coffee creamer without the industrial seed oils and artificial flavors',
    replaces_category: 'Coffee Creamer',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    total_time_minutes: 10,
    servings: 16,
    difficulty: 'easy',
    estimated_cost: 3.50,
    cost_per_serving: 0.22,
    ingredients: [
      { item: 'Oat milk (unsweetened)', amount: '2 cups', notes: 'Or any plant/dairy milk' },
      { item: 'Maple syrup', amount: '2 tbsp', notes: 'Adjust to taste' },
      { item: 'Vanilla extract', amount: '1 tsp', notes: 'Real vanilla, not imitation' },
      { item: 'Pinch of salt', amount: '1/8 tsp', notes: 'Enhances sweetness' },
      { item: 'Coconut cream', amount: '1/4 cup', notes: 'Optional — for extra richness' }
    ],
    instructions: [
      'Blend all ingredients until smooth and frothy.',
      'Taste and adjust sweetness.',
      'Store in a sealed jar or bottle in the fridge.',
      'Shake before each use — natural separation is normal.',
      'Use 2-3 tablespoons per cup of coffee. Lasts 7-10 days.'
    ],
    tips: ['Add 1 tbsp cocoa powder for mocha version', 'Cinnamon + nutmeg for seasonal spice creamer'],
    health_benefits: ['No dipotassium phosphate', 'No carrageenan', 'No artificial flavors', 'No high oleic soybean oil'],
    vs_store_bought: 'Coffee Mate contains corn syrup solids, hydrogenated soybean oil, sodium caseinate, dipotassium phosphate, and artificial flavor. This has 5 real ingredients.',
    kid_friendly: false,
    allergens: ['tree nuts'],
    dietary_tags: ['vegan', 'gluten-free', 'no-artificial-flavors']
  },
  {
    name: 'Homemade Chocolate Milk',
    description: 'Rich chocolate milk with real cocoa and no HFCS or artificial colors',
    replaces_category: 'Chocolate Milk',
    replaces_products: [],
    prep_time_minutes: 5,
    cook_time_minutes: 3,
    total_time_minutes: 8,
    servings: 2,
    difficulty: 'easy',
    estimated_cost: 2.00,
    cost_per_serving: 1.00,
    ingredients: [
      { item: 'Whole milk', amount: '2 cups', notes: 'Or oat/almond milk for dairy-free' },
      { item: 'Cocoa powder (unsweetened)', amount: '2 tbsp', notes: 'Dutch-process for richer flavor' },
      { item: 'Maple syrup or honey', amount: '1-2 tbsp', notes: 'Adjust to taste' },
      { item: 'Vanilla extract', amount: '1/2 tsp', notes: '' },
      { item: 'Pinch of salt', amount: '1/8 tsp', notes: '' }
    ],
    instructions: [
      'Warm 1/4 cup of milk in a small saucepan.',
      'Whisk in cocoa powder until smooth paste forms (no lumps).',
      'Add remaining milk, sweetener, vanilla, and salt.',
      'Whisk until combined. Serve warm or pour over ice.',
      'For cold version: shake all ingredients in a sealed jar.'
    ],
    tips: ['Add a tiny pinch of cinnamon for Mexican hot chocolate style', 'Use a milk frother for extra creamy texture'],
    health_benefits: ['No high fructose corn syrup', 'Real cocoa (antioxidants)', 'No carrageenan', 'No artificial flavors'],
    vs_store_bought: 'Nesquik uses sugar as first ingredient plus corn syrup, soy lecithin, and artificial flavor. Chocolate syrup has HFCS and sodium metabisulfite. This uses real cocoa with real sweetener.',
    kid_friendly: true,
    allergens: ['milk'],
    dietary_tags: ['gluten-free', 'no-artificial-flavors']
  },
  {
    name: 'Green Power Smoothie',
    description: 'Nutrient-dense smoothie that actually tastes good — replaces sugar-bomb bottled smoothies',
    replaces_category: 'Bottled Smoothies',
    replaces_products: [],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    total_time_minutes: 5,
    servings: 2,
    difficulty: 'easy',
    estimated_cost: 4.00,
    cost_per_serving: 2.00,
    ingredients: [
      { item: 'Frozen banana', amount: '1 large', notes: 'Peel and freeze ripe bananas' },
      { item: 'Baby spinach', amount: '2 cups', notes: 'Mild flavor, packed with iron' },
      { item: 'Frozen mango chunks', amount: '1/2 cup', notes: 'Or pineapple' },
      { item: 'Greek yogurt', amount: '1/2 cup', notes: 'Plain, unsweetened' },
      { item: 'Milk or water', amount: '1 cup', notes: 'Adjust for thickness' },
      { item: 'Chia seeds', amount: '1 tbsp', notes: 'Optional — adds omega-3s' }
    ],
    instructions: [
      'Add liquid to blender first (prevents blade cavitation).',
      'Add spinach and blend until smooth — about 30 seconds.',
      'Add frozen fruit, yogurt, and chia seeds.',
      'Blend until completely smooth, 60-90 seconds.',
      'Pour into glasses. Drink immediately for best nutrition.'
    ],
    tips: ['Freeze spinach in portions for grab-and-go smoothie prep', 'Add 1 tbsp peanut butter for protein and creaminess'],
    health_benefits: ['No added sugar', 'Real vegetables', 'Fiber from whole fruit', 'Probiotics from yogurt', 'No "natural flavors" masking sugar'],
    vs_store_bought: 'Naked Juice Green Machine has 53g of sugar per bottle and no fiber (juice, not whole fruit). Odwalla uses "natural flavors" and fruit juice concentrates. This has ~18g natural sugar with 5g fiber from whole fruit and vegetables.',
    kid_friendly: true,
    allergens: ['milk'],
    dietary_tags: ['gluten-free', 'high-protein', 'high-fiber']
  },

  // ── SNACKS ──
  {
    name: 'Soft Pretzel Bites',
    description: 'Warm, chewy pretzel bites with no preservatives or bleached flour',
    replaces_category: 'Pretzels',
    replaces_products: [],
    prep_time_minutes: 20,
    cook_time_minutes: 12,
    total_time_minutes: 90,
    servings: 8,
    difficulty: 'medium',
    estimated_cost: 3.00,
    cost_per_serving: 0.38,
    ingredients: [
      { item: 'Whole wheat flour', amount: '2 cups', notes: 'Or half white/half wheat' },
      { item: 'All-purpose flour', amount: '1 cup', notes: 'For structure' },
      { item: 'Warm water', amount: '1 cup', notes: '110°F — warm to touch' },
      { item: 'Active dry yeast', amount: '1 packet (2.25 tsp)', notes: '' },
      { item: 'Brown sugar', amount: '1 tbsp', notes: 'Feeds the yeast' },
      { item: 'Butter', amount: '2 tbsp', notes: 'Melted' },
      { item: 'Salt', amount: '1 tsp', notes: '' },
      { item: 'Baking soda', amount: '1/4 cup', notes: 'For the boiling water bath' },
      { item: 'Coarse salt', amount: 'For topping', notes: '' }
    ],
    instructions: [
      'Dissolve yeast and sugar in warm water. Let sit 5 minutes until foamy.',
      'Add flour, melted butter, and salt. Knead 5 minutes until smooth.',
      'Cover and let rise 30 minutes.',
      'Preheat oven to 425°F. Bring a pot of water with baking soda to a boil.',
      'Roll dough into ropes and cut into 1-inch bites.',
      'Boil bites in batches for 30 seconds, then place on parchment-lined baking sheet.',
      'Brush with egg wash, sprinkle with coarse salt.',
      'Bake 10-12 minutes until golden brown.'
    ],
    tips: ['Serve with honey mustard or cheese sauce', 'Freeze unbaked bites on a sheet, then bag them — bake from frozen adding 2-3 minutes'],
    health_benefits: ['No BHT', 'No enriched bleached flour', 'No sodium stearoyl lactylate', 'Whole grain fiber'],
    vs_store_bought: 'Snyder\'s pretzels contain enriched flour (stripped of nutrients, then synthetically fortified), corn syrup, and BHT. Rold Gold adds sodium stearoyl lactylate. These use whole wheat with real butter.',
    kid_friendly: true,
    allergens: ['wheat', 'eggs', 'milk'],
    dietary_tags: ['whole-grain']
  },
  {
    name: 'Stovetop Popcorn',
    description: 'Movie theater popcorn at home without diacetyl, TBHQ, or artificial butter flavor',
    replaces_category: 'Microwave Popcorn',
    replaces_products: [],
    prep_time_minutes: 2,
    cook_time_minutes: 5,
    total_time_minutes: 7,
    servings: 4,
    difficulty: 'easy',
    estimated_cost: 1.50,
    cost_per_serving: 0.38,
    ingredients: [
      { item: 'Popcorn kernels', amount: '1/3 cup', notes: 'Makes about 10 cups popped' },
      { item: 'Coconut oil or avocado oil', amount: '2 tbsp', notes: 'High smoke point oils' },
      { item: 'Butter', amount: '2 tbsp', notes: 'Melted (optional)' },
      { item: 'Salt', amount: 'To taste', notes: '' },
      { item: 'Nutritional yeast', amount: '2 tbsp', notes: 'Optional — cheesy flavor without cheese' }
    ],
    instructions: [
      'Heat oil in a large pot over medium-high heat.',
      'Add 3 test kernels — when they pop, oil is ready.',
      'Add remaining kernels in a single layer, cover with lid slightly ajar.',
      'Shake pot occasionally. Once popping slows to 2 seconds between pops, remove from heat.',
      'Toss with melted butter, salt, and nutritional yeast if using.',
      'Serve immediately. Keeps in sealed bag for 2 days.'
    ],
    tips: ['Truffle oil + parmesan is incredible', 'For sweet: drizzle with melted dark chocolate'],
    health_benefits: ['No TBHQ (butane preservative)', 'No diacetyl (linked to popcorn lung)', 'No PFAS from microwave bag lining', 'Whole grain'],
    vs_store_bought: 'Orville Redenbacher contains TBHQ, "butter flavor" (diacetyl), propyl gallate, and the bag lining contains PFAS (forever chemicals). Pop Secret has palm oil and artificial flavor. This has 3-5 real ingredients.',
    kid_friendly: true,
    allergens: ['milk'],
    dietary_tags: ['whole-grain', 'gluten-free']
  },
  {
    name: 'Rosemary Olive Oil Crackers',
    description: 'Thin, crispy crackers with 5 ingredients — replaces preservative-laden boxed crackers',
    replaces_category: 'Crackers',
    replaces_products: [],
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    total_time_minutes: 30,
    servings: 6,
    difficulty: 'easy',
    estimated_cost: 2.50,
    cost_per_serving: 0.42,
    ingredients: [
      { item: 'All-purpose flour', amount: '1.5 cups', notes: 'Or half whole wheat' },
      { item: 'Extra virgin olive oil', amount: '3 tbsp', notes: '' },
      { item: 'Water', amount: '1/3 cup', notes: '' },
      { item: 'Fresh rosemary', amount: '1 tbsp', notes: 'Finely chopped. Or dried: 1 tsp' },
      { item: 'Flaky sea salt', amount: '1 tsp', notes: 'Plus extra for topping' }
    ],
    instructions: [
      'Mix flour, rosemary, and salt. Add olive oil and water.',
      'Knead into a smooth ball — about 2 minutes.',
      'Let rest 10 minutes.',
      'Preheat oven to 400°F.',
      'Roll dough paper-thin on parchment (thinner = crispier).',
      'Score into squares or rectangles with a knife.',
      'Brush lightly with olive oil, sprinkle with flaky salt.',
      'Bake 12-15 minutes until golden and crispy.',
      'Let cool completely — they crisp up more as they cool.'
    ],
    tips: ['Everything bagel seasoning is amazing on these', 'Store in airtight container up to 1 week'],
    health_benefits: ['No BHT/BHA', 'No high fructose corn syrup', 'No soybean oil', 'No sodium bisulfite'],
    vs_store_bought: 'Ritz crackers contain high fructose corn syrup, soybean oil, and TBHQ. Wheat Thins have BHT. These have 5 real ingredients you can pronounce.',
    kid_friendly: true,
    allergens: ['wheat'],
    dietary_tags: ['vegan', 'no-preservatives']
  },
  {
    name: 'Customizable Trail Mix',
    description: 'Build-your-own trail mix with no added oils, sulfites, or candy coating',
    replaces_category: 'Trail Mix',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    total_time_minutes: 22,
    servings: 10,
    difficulty: 'easy',
    estimated_cost: 8.00,
    cost_per_serving: 0.80,
    ingredients: [
      { item: 'Raw almonds', amount: '1 cup', notes: '' },
      { item: 'Raw cashews', amount: '1 cup', notes: '' },
      { item: 'Pumpkin seeds', amount: '1/2 cup', notes: 'Pepitas' },
      { item: 'Unsweetened coconut flakes', amount: '1/2 cup', notes: '' },
      { item: 'Dark chocolate chips (70%+)', amount: '1/2 cup', notes: 'No milk chocolate' },
      { item: 'Dried cranberries', amount: '1/2 cup', notes: 'Look for apple-juice-sweetened, no sulfites' },
      { item: 'Sea salt', amount: '1/2 tsp', notes: '' }
    ],
    instructions: [
      'Preheat oven to 325°F.',
      'Spread nuts and seeds on a baking sheet.',
      'Toast for 10-12 minutes, stirring halfway, until fragrant.',
      'Let cool completely.',
      'Mix all ingredients including chocolate chips, dried fruit, and salt.',
      'Store in mason jars or sealed bags. Keeps 2 weeks at room temp.'
    ],
    tips: ['Add freeze-dried strawberries for color and crunch', 'Portion into snack bags for grab-and-go'],
    health_benefits: ['No sulfur dioxide (sulfites)', 'No soybean oil', 'No candy coating', 'Healthy fats from real nuts', 'No palm oil'],
    vs_store_bought: 'Planters Trail Mix uses peanut oil, corn syrup, and sulfur dioxide on the dried fruit. The M&Ms contain Red 40, Yellow 5, Blue 1, and TBHQ. This uses whole, minimally processed ingredients.',
    kid_friendly: true,
    allergens: ['tree nuts'],
    dietary_tags: ['gluten-free', 'vegan', 'no-artificial-colors']
  },
  {
    name: 'No-Bake Protein Bars',
    description: 'Dense, chewy protein bars without the 30+ ingredient list of commercial bars',
    replaces_category: 'Protein Bars',
    replaces_products: [],
    prep_time_minutes: 15,
    cook_time_minutes: 0,
    total_time_minutes: 75,
    servings: 10,
    difficulty: 'easy',
    estimated_cost: 8.00,
    cost_per_serving: 0.80,
    ingredients: [
      { item: 'Rolled oats', amount: '2 cups', notes: '' },
      { item: 'Peanut butter', amount: '1 cup', notes: 'Natural, just peanuts and salt' },
      { item: 'Honey', amount: '1/3 cup', notes: 'Or maple syrup for vegan' },
      { item: 'Protein powder', amount: '1/2 cup', notes: 'Vanilla or chocolate' },
      { item: 'Dark chocolate chips', amount: '1/3 cup', notes: '' },
      { item: 'Flax seed', amount: '2 tbsp', notes: 'Ground' },
      { item: 'Vanilla extract', amount: '1 tsp', notes: '' },
      { item: 'Salt', amount: '1/4 tsp', notes: '' }
    ],
    instructions: [
      'Mix oats, protein powder, flax, and salt in a large bowl.',
      'Add peanut butter, honey, and vanilla. Stir until fully combined.',
      'Fold in chocolate chips.',
      'Press firmly into a parchment-lined 8x8 pan.',
      'Refrigerate at least 1 hour until firm.',
      'Cut into 10 bars. Store in fridge up to 2 weeks, or freeze for 2 months.'
    ],
    tips: ['Swap PB for almond butter if preferred', 'Press VERY firmly — loose bars crumble'],
    health_benefits: ['No sugar alcohols (maltitol, erythritol)', 'No soy protein isolate', 'No palm kernel oil', 'Whole food ingredients', 'Real fiber from oats and flax'],
    vs_store_bought: 'Clif Bars have 21g sugar plus soy protein isolate, rice flour, and palm kernel oil. Quest Bars use soluble corn fiber (processed), sucralose, and palm kernel oil. These use 8 whole food ingredients with natural sweetness.',
    kid_friendly: true,
    allergens: ['peanuts', 'wheat'],
    dietary_tags: ['high-protein', 'whole-grain']
  },
  {
    name: 'Baked Cheese Crackers',
    description: 'Goldfish-style crackers made with real cheddar — no artificial colors or preservatives',
    replaces_category: 'Goldfish Crackers',
    replaces_products: [],
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    total_time_minutes: 30,
    servings: 8,
    difficulty: 'medium',
    estimated_cost: 4.00,
    cost_per_serving: 0.50,
    ingredients: [
      { item: 'Sharp cheddar cheese', amount: '8 oz', notes: 'Finely shredded' },
      { item: 'Butter', amount: '4 tbsp', notes: 'Cold, cubed' },
      { item: 'All-purpose flour', amount: '1 cup', notes: '' },
      { item: 'Salt', amount: '1/2 tsp', notes: '' },
      { item: 'Smoked paprika', amount: '1/2 tsp', notes: 'Optional — adds color naturally' },
      { item: 'Water', amount: '2-3 tbsp', notes: 'Ice cold' }
    ],
    instructions: [
      'Pulse cheese, butter, flour, salt, and paprika in food processor until sandy.',
      'Add ice water 1 tablespoon at a time until dough holds together.',
      'Wrap in plastic, refrigerate 30 minutes.',
      'Preheat oven to 375°F.',
      'Roll dough very thin (1/8 inch) between parchment sheets.',
      'Cut into small squares or use fish-shaped cookie cutter.',
      'Bake 12-15 minutes until golden and crispy.',
      'Cool completely — they continue crisping.'
    ],
    tips: ['Use mini cookie cutters for fun shapes kids love', 'Add 1/4 tsp cayenne for adult version'],
    health_benefits: ['No annatto extract', 'Color from real paprika not dyes', 'No autolyzed yeast', 'Real cheddar vs cheese powder'],
    vs_store_bought: 'Goldfish contain enriched wheat flour, cheddar cheese powder (not real cheese), annatto extract, autolyzed yeast extract (hidden MSG), and various preservatives. These use 6 real ingredients with actual cheddar.',
    kid_friendly: true,
    allergens: ['wheat', 'milk'],
    dietary_tags: ['no-artificial-colors', 'no-preservatives']
  },

  // ── CONDIMENTS & SAUCES ──
  {
    name: 'Homemade Ketchup',
    description: 'Rich tomato ketchup without high fructose corn syrup or natural flavors',
    replaces_category: 'Ketchup',
    replaces_products: [],
    prep_time_minutes: 5,
    cook_time_minutes: 25,
    total_time_minutes: 30,
    servings: 24,
    difficulty: 'easy',
    estimated_cost: 4.00,
    cost_per_serving: 0.17,
    ingredients: [
      { item: 'Tomato paste', amount: '6 oz can', notes: 'Look for BPA-free can' },
      { item: 'Apple cider vinegar', amount: '1/4 cup', notes: '' },
      { item: 'Water', amount: '1/4 cup', notes: '' },
      { item: 'Honey or maple syrup', amount: '2 tbsp', notes: '' },
      { item: 'Onion powder', amount: '1/2 tsp', notes: '' },
      { item: 'Garlic powder', amount: '1/4 tsp', notes: '' },
      { item: 'Salt', amount: '1/2 tsp', notes: '' },
      { item: 'Allspice', amount: '1/8 tsp', notes: '' }
    ],
    instructions: [
      'Whisk all ingredients together in a saucepan.',
      'Bring to a gentle simmer over medium heat.',
      'Reduce heat to low, simmer 20 minutes, stirring occasionally.',
      'Taste and adjust salt/sweetness.',
      'Cool and transfer to a squeeze bottle or jar.',
      'Refrigerate — keeps 3-4 weeks.'
    ],
    tips: ['Add a pinch of cayenne for kick', 'Double the batch — it goes fast'],
    health_benefits: ['No high fructose corn syrup', 'No natural flavors', 'No corn syrup', 'Lower sugar than Heinz'],
    vs_store_bought: 'Heinz ketchup lists tomato concentrate, distilled vinegar, high fructose corn syrup, corn syrup, and "natural flavoring." Hunt\'s uses corn syrup. This has 8 real ingredients with 60% less sugar.',
    kid_friendly: true,
    allergens: [],
    dietary_tags: ['vegan', 'gluten-free', 'no-artificial-flavors']
  },
  {
    name: 'Smoky BBQ Sauce',
    description: 'Kansas City-style BBQ sauce from scratch — no HFCS, no caramel color',
    replaces_category: 'BBQ Sauce',
    replaces_products: [],
    prep_time_minutes: 5,
    cook_time_minutes: 20,
    total_time_minutes: 25,
    servings: 16,
    difficulty: 'easy',
    estimated_cost: 5.00,
    cost_per_serving: 0.31,
    ingredients: [
      { item: 'Tomato paste', amount: '6 oz', notes: '' },
      { item: 'Apple cider vinegar', amount: '1/4 cup', notes: '' },
      { item: 'Water', amount: '1/4 cup', notes: '' },
      { item: 'Brown sugar', amount: '3 tbsp', notes: '' },
      { item: 'Smoked paprika', amount: '1 tbsp', notes: 'This is the key smoky flavor' },
      { item: 'Worcestershire sauce', amount: '1 tbsp', notes: '' },
      { item: 'Mustard powder', amount: '1 tsp', notes: '' },
      { item: 'Garlic powder', amount: '1 tsp', notes: '' },
      { item: 'Onion powder', amount: '1 tsp', notes: '' },
      { item: 'Black pepper', amount: '1/2 tsp', notes: '' },
      { item: 'Salt', amount: '1/2 tsp', notes: '' }
    ],
    instructions: [
      'Combine all ingredients in a saucepan and whisk smooth.',
      'Bring to a simmer over medium heat.',
      'Reduce heat and simmer 15-20 minutes until thickened.',
      'Taste — add more sugar for sweeter, more vinegar for tangier.',
      'Cool and store in a jar. Keeps 3 weeks refrigerated.'
    ],
    tips: ['Add 1 tbsp bourbon for adult version', 'Chipotle powder adds heat and smoke'],
    health_benefits: ['No high fructose corn syrup', 'No caramel color (4-MEI)', 'No sodium benzoate', 'No modified food starch'],
    vs_store_bought: 'Sweet Baby Ray\'s first ingredient is high fructose corn syrup, followed by distilled vinegar and tomato paste — plus caramel color, sodium benzoate, and modified food starch. This puts tomato first with 70% less sugar.',
    kid_friendly: true,
    allergens: [],
    dietary_tags: ['vegan', 'gluten-free']
  },
  {
    name: 'Classic Vinaigrette',
    description: 'The only salad dressing you need — 5 ingredients, 2 minutes, no soybean oil',
    replaces_category: 'Salad Dressing',
    replaces_products: [],
    prep_time_minutes: 2,
    cook_time_minutes: 0,
    total_time_minutes: 2,
    servings: 8,
    difficulty: 'easy',
    estimated_cost: 3.00,
    cost_per_serving: 0.38,
    ingredients: [
      { item: 'Extra virgin olive oil', amount: '1/2 cup', notes: 'Good quality makes a difference' },
      { item: 'Red wine vinegar', amount: '3 tbsp', notes: 'Or balsamic, lemon juice, etc.' },
      { item: 'Dijon mustard', amount: '1 tsp', notes: 'Acts as emulsifier' },
      { item: 'Salt', amount: '1/2 tsp', notes: '' },
      { item: 'Black pepper', amount: '1/4 tsp', notes: '' }
    ],
    instructions: [
      'Add all ingredients to a jar with a tight lid.',
      'Shake vigorously for 15 seconds until emulsified.',
      'Taste on a piece of lettuce and adjust seasoning.',
      'Store in fridge up to 2 weeks. Shake before each use.'
    ],
    tips: ['Add minced garlic, herbs, or shallot for variations', 'The 3:1 oil-to-acid ratio works with any vinegar'],
    health_benefits: ['No soybean oil', 'No canola oil', 'No xanthan gum', 'No calcium disodium EDTA', 'Heart-healthy olive oil fats'],
    vs_store_bought: 'Kraft Italian uses soybean oil, corn syrup, calcium disodium EDTA, and "natural flavor." Wishbone contains polysorbate 60. Even "olive oil" dressings are mostly soybean oil. This is 100% real olive oil.',
    kid_friendly: true,
    allergens: ['mustard'],
    dietary_tags: ['vegan', 'gluten-free', 'keto']
  },
  {
    name: 'Homemade Mayonnaise',
    description: 'Creamy mayo in 5 minutes with an immersion blender — no soybean oil, no EDTA',
    replaces_category: 'Mayonnaise',
    replaces_products: [],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    total_time_minutes: 5,
    servings: 16,
    difficulty: 'easy',
    estimated_cost: 4.00,
    cost_per_serving: 0.25,
    ingredients: [
      { item: 'Egg (room temperature)', amount: '1 large', notes: 'Use pasteurized if concerned about raw eggs' },
      { item: 'Avocado oil or light olive oil', amount: '1 cup', notes: 'Neutral flavor — don\'t use extra virgin' },
      { item: 'Lemon juice', amount: '1 tbsp', notes: 'Fresh' },
      { item: 'Dijon mustard', amount: '1 tsp', notes: '' },
      { item: 'Salt', amount: '1/2 tsp', notes: '' }
    ],
    instructions: [
      'Add egg, lemon juice, mustard, and salt to a tall narrow container (mason jar works).',
      'Pour oil on top — do NOT stir yet.',
      'Place immersion blender at the bottom, touching the base.',
      'Blend on high without moving for 15 seconds — watch it emulsify from the bottom up.',
      'Slowly lift the blender up through the mixture until fully emulsified.',
      'Store in fridge. Use within 1 week.'
    ],
    tips: ['Add roasted garlic for aioli', 'Add chipotle pepper for spicy mayo'],
    health_benefits: ['No soybean oil', 'No calcium disodium EDTA', 'No potassium sorbate', 'Healthy fats from avocado oil'],
    vs_store_bought: 'Hellmann\'s uses soybean oil, modified food starch, calcium disodium EDTA, and "natural flavors." Duke\'s uses soybean oil. Avocado-oil brands like Primal Kitchen cost $9+. This costs $4 and takes 5 minutes.',
    kid_friendly: true,
    allergens: ['eggs', 'mustard'],
    dietary_tags: ['gluten-free', 'keto', 'no-preservatives']
  },

  // ── MEALS ──
  {
    name: 'Easy Pizza Dough',
    description: 'Homemade pizza dough that beats frozen — no BHT, no L-cysteine, no dough conditioners',
    replaces_category: 'Frozen Pizza',
    replaces_products: [],
    prep_time_minutes: 15,
    cook_time_minutes: 12,
    total_time_minutes: 75,
    servings: 8,
    difficulty: 'medium',
    estimated_cost: 2.00,
    cost_per_serving: 0.25,
    ingredients: [
      { item: 'All-purpose flour', amount: '3 cups', notes: 'Or half whole wheat' },
      { item: 'Warm water', amount: '1 cup', notes: '110°F' },
      { item: 'Active dry yeast', amount: '1 packet', notes: '' },
      { item: 'Olive oil', amount: '2 tbsp', notes: '' },
      { item: 'Honey', amount: '1 tsp', notes: 'Feeds the yeast' },
      { item: 'Salt', amount: '1 tsp', notes: '' }
    ],
    instructions: [
      'Dissolve yeast and honey in warm water. Wait 5 minutes until foamy.',
      'Add flour, olive oil, and salt. Mix until dough forms.',
      'Knead on floured surface 5 minutes until smooth and elastic.',
      'Place in oiled bowl, cover, let rise 45 minutes.',
      'Preheat oven to 475°F (or as hot as it goes).',
      'Stretch dough on a floured surface or oiled baking sheet.',
      'Add sauce, cheese, and toppings.',
      'Bake 10-12 minutes until crust is golden and cheese is bubbly.'
    ],
    tips: ['For crispier crust, preheat a baking sheet or pizza stone', 'This dough freezes beautifully — make a double batch'],
    health_benefits: ['No BHT/BHA', 'No L-cysteine (derived from human hair or duck feathers)', 'No dough conditioners (DATEM, sodium stearoyl lactylate)', 'No partially hydrogenated oils'],
    vs_store_bought: 'DiGiorno contains L-cysteine, DATEM, BHT, modified food starch, sodium aluminum phosphate, and artificial flavor. Tombstone has BHA. This has 6 ingredients, all recognizable.',
    kid_friendly: true,
    allergens: ['wheat'],
    dietary_tags: ['vegan']
  },
  {
    name: '15-Minute Ramen',
    description: 'Real ramen broth from scratch — replaces MSG-laden instant noodle packets',
    replaces_category: 'Instant Ramen',
    replaces_products: [],
    prep_time_minutes: 5,
    cook_time_minutes: 10,
    total_time_minutes: 15,
    servings: 2,
    difficulty: 'easy',
    estimated_cost: 4.00,
    cost_per_serving: 2.00,
    ingredients: [
      { item: 'Chicken or vegetable broth', amount: '4 cups', notes: 'Low sodium' },
      { item: 'Soy sauce', amount: '2 tbsp', notes: 'Or tamari for gluten-free' },
      { item: 'Sesame oil', amount: '1 tsp', notes: '' },
      { item: 'Fresh ginger', amount: '1 inch piece', notes: 'Sliced thin' },
      { item: 'Garlic', amount: '2 cloves', notes: 'Minced' },
      { item: 'Ramen noodles or rice noodles', amount: '6 oz', notes: 'Fresh or dried' },
      { item: 'Soft-boiled egg', amount: '2', notes: 'Optional' },
      { item: 'Green onions', amount: '2 stalks', notes: 'Sliced' },
      { item: 'Sriracha', amount: 'To taste', notes: 'Optional' }
    ],
    instructions: [
      'Bring broth to a boil with ginger and garlic.',
      'Add soy sauce and sesame oil.',
      'Cook noodles in the broth according to package directions.',
      'Remove ginger slices.',
      'Ladle into bowls, top with soft-boiled egg halves and green onions.',
      'Add sriracha to taste.'
    ],
    tips: ['Add miso paste for even deeper flavor', 'Leftover roasted chicken makes this a complete meal in minutes'],
    health_benefits: ['No MSG (monosodium glutamate)', 'No TBHQ', 'No palm oil', 'No sodium tripolyphosphate', 'Real vegetables and protein'],
    vs_store_bought: 'Maruchan Instant contains TBHQ, MSG, palm oil, sodium tripolyphosphate, caramel color, and over 1,500mg sodium per serving. Top Ramen is similar. This has real broth, real aromatics, and 60% less sodium.',
    kid_friendly: true,
    allergens: ['soy', 'wheat', 'eggs'],
    dietary_tags: ['no-msg', 'no-preservatives']
  },
  {
    name: 'Freezer Breakfast Burritos',
    description: 'Batch-prep burritos that microwave perfectly — replaces frozen breakfast sandwiches',
    replaces_category: 'Frozen Breakfast',
    replaces_products: [],
    prep_time_minutes: 20,
    cook_time_minutes: 10,
    total_time_minutes: 30,
    servings: 8,
    difficulty: 'easy',
    estimated_cost: 10.00,
    cost_per_serving: 1.25,
    ingredients: [
      { item: 'Eggs', amount: '8 large', notes: 'Scrambled soft' },
      { item: 'Black beans', amount: '1 can (15 oz)', notes: 'Drained and rinsed' },
      { item: 'Shredded cheese', amount: '1 cup', notes: 'Cheddar or Mexican blend' },
      { item: 'Bell pepper', amount: '1 large', notes: 'Diced' },
      { item: 'Onion', amount: '1/2', notes: 'Diced' },
      { item: 'Salsa', amount: '1/2 cup', notes: '' },
      { item: 'Large flour tortillas', amount: '8', notes: '' },
      { item: 'Salt and pepper', amount: 'To taste', notes: '' },
      { item: 'Cumin', amount: '1 tsp', notes: 'Optional' }
    ],
    instructions: [
      'Sauté pepper and onion until soft, about 5 minutes.',
      'Scramble eggs with cumin, salt, and pepper. Keep slightly underdone.',
      'Warm tortillas in microwave 15 seconds to make pliable.',
      'Divide eggs, beans, veggies, cheese, and salsa among tortillas.',
      'Roll tightly, tucking in sides.',
      'Wrap each burrito in foil, then place all in a freezer bag.',
      'To reheat: remove foil, wrap in damp paper towel, microwave 2-3 minutes.',
      'Keeps frozen for 3 months.'
    ],
    tips: ['Add cooked sausage or bacon for heartier version', 'Label with date and variety — make 2-3 different kinds'],
    health_benefits: ['No sodium nitrite', 'No BHA/BHT', 'No "mechanically separated" meat', 'Real eggs vs egg product', 'Fiber from beans'],
    vs_store_bought: 'Jimmy Dean frozen sandwiches contain sodium nitrite, BHA, BHT, caramel color, "mechanically separated turkey," and modified food starch. Hot Pockets contain TBHQ and sodium aluminum phosphate. These are real food.',
    kid_friendly: true,
    allergens: ['eggs', 'wheat', 'milk'],
    dietary_tags: ['high-protein', 'meal-prep']
  },
  {
    name: 'Creamy Tomato Soup',
    description: 'Silky tomato soup from canned tomatoes — beats any condensed soup can',
    replaces_category: 'Canned Soup',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    total_time_minutes: 35,
    servings: 4,
    difficulty: 'easy',
    estimated_cost: 5.00,
    cost_per_serving: 1.25,
    ingredients: [
      { item: 'Canned whole tomatoes', amount: '28 oz can', notes: 'San Marzano if possible' },
      { item: 'Onion', amount: '1 medium', notes: 'Diced' },
      { item: 'Garlic', amount: '3 cloves', notes: 'Minced' },
      { item: 'Olive oil', amount: '2 tbsp', notes: '' },
      { item: 'Vegetable or chicken broth', amount: '1 cup', notes: '' },
      { item: 'Heavy cream', amount: '1/4 cup', notes: 'Or coconut cream for dairy-free' },
      { item: 'Fresh basil', amount: 'Handful', notes: '' },
      { item: 'Salt and pepper', amount: 'To taste', notes: '' },
      { item: 'Red pepper flakes', amount: 'Pinch', notes: 'Optional' }
    ],
    instructions: [
      'Heat olive oil in a pot. Sauté onion 5 minutes until soft.',
      'Add garlic, cook 1 minute until fragrant.',
      'Add canned tomatoes (with juice) and broth. Break up tomatoes with a spoon.',
      'Simmer 20 minutes.',
      'Add basil. Blend with immersion blender until smooth.',
      'Stir in cream, season with salt and pepper.',
      'Serve with crusty bread or grilled cheese.'
    ],
    tips: ['Roast the tomatoes first for deeper flavor', 'Freezes perfectly for up to 3 months'],
    health_benefits: ['No modified food starch', 'No MSG', 'No high fructose corn syrup', 'No BPA (if choosing BPA-free cans)', 'Real vegetables'],
    vs_store_bought: 'Campbell\'s Tomato Soup contains high fructose corn syrup, modified food starch, and over 800mg sodium per serving. Progresso uses MSG and corn starch. This has 9 real ingredients with less sodium and no sweeteners.',
    kid_friendly: true,
    allergens: ['milk'],
    dietary_tags: ['gluten-free', 'low-sodium']
  },
  {
    name: 'Crispy Homemade Waffles',
    description: 'Golden waffles that freeze and toast perfectly — replaces Eggo and other frozen waffles',
    replaces_category: 'Frozen Waffles',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    total_time_minutes: 30,
    servings: 6,
    difficulty: 'easy',
    estimated_cost: 3.00,
    cost_per_serving: 0.50,
    ingredients: [
      { item: 'All-purpose flour', amount: '2 cups', notes: '' },
      { item: 'Eggs', amount: '2 large', notes: 'Separated' },
      { item: 'Milk', amount: '1.5 cups', notes: '' },
      { item: 'Butter', amount: '1/3 cup', notes: 'Melted' },
      { item: 'Sugar', amount: '1 tbsp', notes: '' },
      { item: 'Baking powder', amount: '1 tbsp', notes: '' },
      { item: 'Salt', amount: '1/2 tsp', notes: '' },
      { item: 'Vanilla extract', amount: '1 tsp', notes: '' }
    ],
    instructions: [
      'Whisk flour, sugar, baking powder, and salt.',
      'In separate bowl, mix egg yolks, milk, melted butter, and vanilla.',
      'Beat egg whites until stiff peaks form.',
      'Combine wet and dry ingredients — don\'t overmix.',
      'Gently fold in egg whites (this is the crispy secret).',
      'Cook in preheated waffle iron until golden.',
      'To freeze: cool completely, place in single layer in freezer, then bag.',
      'Reheat: straight from freezer into toaster.'
    ],
    tips: ['Whipped egg whites are the secret to crispy exterior', 'Make a double batch — freeze extras for weekday breakfasts'],
    health_benefits: ['No TBHQ', 'No sodium aluminum phosphate', 'No dextrose', 'No calcium caseinate', 'No artificial flavors'],
    vs_store_bought: 'Eggo waffles contain enriched flour, dextrose, palm oil, TBHQ, sodium aluminum phosphate, calcium caseinate, natural and artificial flavor, and soy lecithin. This has 8 real ingredients.',
    kid_friendly: true,
    allergens: ['wheat', 'eggs', 'milk'],
    dietary_tags: []
  },
  {
    name: 'Simple Sandwich Bread',
    description: 'Soft, sliceable bread with no dough conditioners or preservatives — freezes beautifully',
    replaces_category: 'Sliced Bread',
    replaces_products: [],
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    total_time_minutes: 120,
    servings: 12,
    difficulty: 'medium',
    estimated_cost: 2.50,
    cost_per_serving: 0.21,
    ingredients: [
      { item: 'All-purpose flour', amount: '3 cups', notes: '' },
      { item: 'Whole wheat flour', amount: '1/2 cup', notes: 'Optional — adds nutrition' },
      { item: 'Warm water', amount: '1 cup', notes: '110°F' },
      { item: 'Butter', amount: '2 tbsp', notes: 'Softened' },
      { item: 'Honey', amount: '2 tbsp', notes: '' },
      { item: 'Active dry yeast', amount: '1 packet', notes: '' },
      { item: 'Salt', amount: '1.5 tsp', notes: '' }
    ],
    instructions: [
      'Dissolve yeast in warm water with honey. Wait 5 minutes.',
      'Add flour, butter, and salt. Mix and knead 8-10 minutes until smooth.',
      'Place in oiled bowl, cover with towel, rise 45 minutes until doubled.',
      'Punch down, shape into a loaf, place in greased 9x5 loaf pan.',
      'Cover, let rise 30 minutes.',
      'Preheat oven to 375°F. Bake 28-32 minutes until golden.',
      'Remove from pan, cool completely on wire rack before slicing.',
      'Slice and freeze what you won\'t use in 3 days.'
    ],
    tips: ['Cool COMPLETELY before slicing or it\'ll squish', 'Pre-slice and freeze — pull out slices as needed'],
    health_benefits: ['No DATEM', 'No azodicarbonamide (banned in EU, used in yoga mats)', 'No calcium peroxide', 'No sodium stearoyl lactylate', 'No calcium sulfate'],
    vs_store_bought: 'Wonder Bread contains DATEM, calcium sulfate, monoglycerides, calcium peroxide, and azodicarbonamide (banned in EU and Australia). Sara Lee has sodium stearoyl lactylate, monocalcium phosphate, and "enzymes." This has 7 ingredients.',
    kid_friendly: true,
    allergens: ['wheat', 'milk'],
    dietary_tags: ['no-preservatives']
  },

  // ── BREAKFAST ──
  {
    name: 'Homemade Toaster Pastries',
    description: 'Flaky pastries with real fruit filling — Pop-Tarts with actual food ingredients',
    replaces_category: 'Toaster Pastries',
    replaces_products: [],
    prep_time_minutes: 30,
    cook_time_minutes: 15,
    total_time_minutes: 45,
    servings: 8,
    difficulty: 'medium',
    estimated_cost: 5.00,
    cost_per_serving: 0.63,
    ingredients: [
      { item: 'All-purpose flour', amount: '2 cups', notes: '' },
      { item: 'Cold butter', amount: '1/2 cup', notes: 'Cubed' },
      { item: 'Cream cheese', amount: '4 oz', notes: 'Cold' },
      { item: 'Ice water', amount: '2-3 tbsp', notes: '' },
      { item: 'Fruit jam (any flavor)', amount: '1/2 cup', notes: 'Good quality, fruit-first ingredient' },
      { item: 'Egg', amount: '1', notes: 'For egg wash' },
      { item: 'Powdered sugar', amount: '1/2 cup', notes: 'For glaze' },
      { item: 'Milk', amount: '1 tbsp', notes: 'For glaze' },
      { item: 'Vanilla extract', amount: '1/2 tsp', notes: 'For glaze' }
    ],
    instructions: [
      'Pulse flour, butter, and cream cheese in food processor until pea-sized crumbs.',
      'Add ice water until dough just holds together.',
      'Divide in half, flatten into rectangles, wrap, and refrigerate 30 minutes.',
      'Preheat oven to 375°F.',
      'Roll each half into a rectangle, cut into equal rectangles (about 3x4 inches).',
      'Place 1 tablespoon jam on half the rectangles. Top with remaining pieces.',
      'Seal edges with a fork. Cut small vents in top. Brush with egg wash.',
      'Bake 14-16 minutes until golden.',
      'Mix glaze ingredients, drizzle over cooled pastries.'
    ],
    tips: ['Freeze assembled but unbaked pastries — bake from frozen adding 3 minutes', 'Nutella filling is incredible'],
    health_benefits: ['No TBHQ', 'No Yellow 6/Red 40/Blue 1', 'No sodium pyrophosphate', 'Real fruit vs "fruit-flavored" filling', 'No soybean oil'],
    vs_store_bought: 'Pop-Tarts contain TBHQ, corn syrup, soybean oil, dextrose, Yellow 6, Red 40, Blue 1, sodium pyrophosphate, and "natural and artificial flavor." The fruit filling is mostly corn syrup. These use real jam and butter.',
    kid_friendly: true,
    allergens: ['wheat', 'milk', 'eggs'],
    dietary_tags: ['no-artificial-colors']
  },
  {
    name: 'Instant Pot Yogurt',
    description: 'Thick, creamy yogurt with just 2 ingredients — no gelatin, no pectin, no sweeteners',
    replaces_category: 'Yogurt',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    total_time_minutes: 540,
    servings: 8,
    difficulty: 'easy',
    estimated_cost: 3.50,
    cost_per_serving: 0.44,
    ingredients: [
      { item: 'Whole milk', amount: '1/2 gallon', notes: 'Not ultra-pasteurized' },
      { item: 'Plain yogurt with live cultures', amount: '2 tbsp', notes: 'This is your starter — use once, then save from each batch' }
    ],
    instructions: [
      'Pour milk into Instant Pot inner pot.',
      'Press Yogurt button, then Adjust until it says "boil." Wait (~30 min).',
      'When it beeps, remove inner pot. Cool milk to 110°F (use thermometer).',
      'Whisk in yogurt starter.',
      'Return pot, press Yogurt, set for 8 hours (longer = tangier).',
      'Refrigerate at least 4 hours to thicken.',
      'For Greek yogurt: strain through cheesecloth 2-4 hours.',
      'Save 2 tbsp from each batch as starter for next time.'
    ],
    tips: ['The whey strained off Greek yogurt is great in smoothies and baking', 'Add vanilla and honey AFTER making — not before'],
    health_benefits: ['Live probiotics (billions vs millions in commercial)', 'No pectin or gelatin', 'No "natural flavors"', 'No artificial sweeteners', 'No added sugar'],
    vs_store_bought: 'Yoplait contains modified corn starch, potassium sorbate, "natural flavor," and 18g added sugar. Dannon uses pectin, modified food starch, and sucralose in light versions. Homemade is just milk and cultures — add your own toppings.',
    kid_friendly: true,
    allergens: ['milk'],
    dietary_tags: ['gluten-free', 'probiotic', 'no-added-sugar']
  },
  {
    name: 'Blueberry Oat Muffins',
    description: 'Moist, tender muffins with real blueberries — no propylene glycol or artificial blueberry bits',
    replaces_category: 'Muffins',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 22,
    total_time_minutes: 32,
    servings: 12,
    difficulty: 'easy',
    estimated_cost: 5.00,
    cost_per_serving: 0.42,
    ingredients: [
      { item: 'All-purpose flour', amount: '1.5 cups', notes: '' },
      { item: 'Rolled oats', amount: '1/2 cup', notes: '' },
      { item: 'Fresh or frozen blueberries', amount: '1.5 cups', notes: 'Toss frozen in flour to prevent sinking' },
      { item: 'Butter', amount: '1/3 cup', notes: 'Melted' },
      { item: 'Egg', amount: '1 large', notes: '' },
      { item: 'Milk', amount: '1/2 cup', notes: '' },
      { item: 'Brown sugar', amount: '1/3 cup', notes: '' },
      { item: 'Baking powder', amount: '2 tsp', notes: '' },
      { item: 'Salt', amount: '1/2 tsp', notes: '' },
      { item: 'Vanilla extract', amount: '1 tsp', notes: '' }
    ],
    instructions: [
      'Preheat oven to 375°F. Line muffin tin with papers.',
      'Mix flour, oats, baking powder, and salt.',
      'In separate bowl, whisk melted butter, egg, milk, sugar, and vanilla.',
      'Pour wet into dry, stir until just combined — lumps are fine.',
      'Gently fold in blueberries.',
      'Divide evenly among 12 cups.',
      'Bake 20-22 minutes until golden and toothpick comes out clean.',
      'Cool 5 minutes in pan, then remove to wire rack.'
    ],
    tips: ['Freeze individually wrapped muffins — microwave 30 seconds for warm breakfast', 'Sprinkle raw sugar on top before baking for crunchy tops'],
    health_benefits: ['Real blueberries (antioxidants)', 'No propylene glycol', 'No artificial blueberry bits', 'No sodium aluminum phosphate', 'Fiber from oats'],
    vs_store_bought: 'Entenmann\'s muffins contain corn syrup, soybean oil, propylene glycol, sodium aluminum phosphate, artificial flavor, and "blueberry bits" (dextrose, flour, partially hydrogenated oil, artificial color). These use real blueberries.',
    kid_friendly: true,
    allergens: ['wheat', 'eggs', 'milk'],
    dietary_tags: ['whole-grain']
  },
  {
    name: 'Turkey Sausage Patties',
    description: 'Savory breakfast sausage without sodium nitrite or BHA — freezer-friendly',
    replaces_category: 'Breakfast Sausage',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 8,
    total_time_minutes: 18,
    servings: 8,
    difficulty: 'easy',
    estimated_cost: 6.00,
    cost_per_serving: 0.75,
    ingredients: [
      { item: 'Ground turkey', amount: '1 lb', notes: 'Dark meat has more flavor' },
      { item: 'Maple syrup', amount: '1 tbsp', notes: '' },
      { item: 'Sage', amount: '1 tsp', notes: 'Dried (or 1 tbsp fresh)' },
      { item: 'Thyme', amount: '1/2 tsp', notes: 'Dried' },
      { item: 'Garlic powder', amount: '1/2 tsp', notes: '' },
      { item: 'Salt', amount: '3/4 tsp', notes: '' },
      { item: 'Black pepper', amount: '1/2 tsp', notes: '' },
      { item: 'Red pepper flakes', amount: '1/4 tsp', notes: 'Optional' }
    ],
    instructions: [
      'Mix all ingredients gently with hands — don\'t overwork.',
      'Form into 8 patties, about 1/2 inch thick.',
      'Cook in skillet over medium heat, 3-4 minutes per side.',
      'Internal temp should reach 165°F.',
      'To freeze: place cooked and cooled patties in single layer on sheet pan, freeze, then bag.'
    ],
    tips: ['Make a double or triple batch for the month', 'Add grated apple for moisture and sweetness'],
    health_benefits: ['No sodium nitrite (linked to colorectal cancer)', 'No BHA/BHT', 'No sodium phosphate', 'No "natural flavors"', 'Lower fat than pork sausage'],
    vs_store_bought: 'Jimmy Dean sausage contains BHA, BHT, and "natural flavors." Banquet patties contain sodium phosphate, corn syrup, and caramel color. Oscar Mayer contains sodium nitrite and sodium erythorbate. These have 8 real spice-rack ingredients.',
    kid_friendly: true,
    allergens: [],
    dietary_tags: ['gluten-free', 'high-protein', 'no-preservatives']
  },

  // ── KIDS SPECIFIC ──
  {
    name: 'DIY Lunchables',
    description: 'Homemade bento-style lunchbox with real food instead of processed meat and cheese product',
    replaces_category: 'Lunchables',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    total_time_minutes: 10,
    servings: 1,
    difficulty: 'easy',
    estimated_cost: 3.00,
    cost_per_serving: 3.00,
    ingredients: [
      { item: 'Sliced deli turkey (no nitrates)', amount: '2 oz', notes: 'Look for "uncured" or nitrate-free' },
      { item: 'Real cheddar cheese', amount: '1 oz', notes: 'Cubed or sliced' },
      { item: 'Whole grain crackers', amount: '8-10', notes: '' },
      { item: 'Grapes or berries', amount: '1/2 cup', notes: '' },
      { item: 'Hummus or guacamole', amount: '2 tbsp', notes: 'For dipping' },
      { item: 'Baby carrots or cucumber slices', amount: 'Handful', notes: '' }
    ],
    instructions: [
      'Use a bento box or divided container.',
      'Roll turkey slices, arrange with cheese cubes.',
      'Add crackers in separate compartment.',
      'Add fruit and veggies.',
      'Put hummus in a small container with lid.',
      'Keep cold with an ice pack. Prep 3-5 days ahead for the week.'
    ],
    tips: ['Use cookie cutters on cheese and meat for fun shapes', 'Let kids build their own — they eat more when they choose'],
    health_benefits: ['No sodium nitrite', 'Real cheese vs "cheese product"', 'No Yellow 5/6', 'Fresh fruit vs fruit-flavored gummies', 'Actual vegetables'],
    vs_store_bought: 'Lunchables Turkey & Cheddar contains sodium nitrite, modified food starch, sodium phosphate, smoke flavoring, dextrose, and the "cheese" is actually "pasteurized prepared cheese product." The Capri Sun included has high fructose corn syrup and artificial colors.',
    kid_friendly: true,
    allergens: ['wheat', 'milk'],
    dietary_tags: ['high-protein', 'no-preservatives']
  },
  {
    name: 'Yogurt Tubes',
    description: 'Homemade Go-Gurt in reusable silicone tubes — real fruit, no artificial sweeteners',
    replaces_category: 'Yogurt Tubes',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    total_time_minutes: 130,
    servings: 8,
    difficulty: 'easy',
    estimated_cost: 4.00,
    cost_per_serving: 0.50,
    ingredients: [
      { item: 'Plain whole milk yogurt', amount: '2 cups', notes: 'Greek or regular' },
      { item: 'Frozen mixed berries', amount: '1 cup', notes: 'Thawed' },
      { item: 'Honey', amount: '2 tbsp', notes: 'Adjust to taste' },
      { item: 'Vanilla extract', amount: '1/2 tsp', notes: '' }
    ],
    instructions: [
      'Blend berries until smooth (or leave some chunks for texture).',
      'Mix yogurt, berry puree, honey, and vanilla.',
      'Pour into silicone freezer tubes (available on Amazon).',
      'Freeze at least 2 hours for frozen yogurt tubes.',
      'Or refrigerate for squeeze yogurt tubes.',
      'Keeps frozen 2 months, refrigerated 5 days.'
    ],
    tips: ['Buy reusable silicone push-pop tubes — they last years', 'Make different flavors: mango, strawberry-banana, peach'],
    health_benefits: ['No Red 40', 'No potassium sorbate', 'No tricalcium phosphate', 'No carrageenan', 'Real probiotics from yogurt', 'Real fruit'],
    vs_store_bought: 'Go-Gurt contains modified corn starch, potassium sorbate, carrageenan, Red 40, Blue 1, and "natural flavor" with only 5% real fruit. These are real yogurt with real berries.',
    kid_friendly: true,
    allergens: ['milk'],
    dietary_tags: ['gluten-free', 'probiotic']
  },
  {
    name: 'Fresh Fruit Cups',
    description: 'Real fruit cups in light juice — no heavy syrup, no artificial sweeteners',
    replaces_category: 'Fruit Cups',
    replaces_products: [],
    prep_time_minutes: 15,
    cook_time_minutes: 0,
    total_time_minutes: 15,
    servings: 6,
    difficulty: 'easy',
    estimated_cost: 5.00,
    cost_per_serving: 0.83,
    ingredients: [
      { item: 'Mixed fresh fruit', amount: '4 cups', notes: 'Diced: peaches, strawberries, grapes, mandarin segments, pineapple' },
      { item: '100% orange juice', amount: '1/2 cup', notes: '' },
      { item: 'Honey', amount: '1 tbsp', notes: 'Optional' },
      { item: 'Fresh mint', amount: 'A few leaves', notes: 'Optional — finely chopped' }
    ],
    instructions: [
      'Cut all fruit into small, uniform pieces.',
      'Toss gently with orange juice and honey.',
      'Divide into 6 small jars or containers.',
      'Refrigerate. Best eaten within 3-4 days.',
      'Pack in lunchboxes with an ice pack.'
    ],
    tips: ['Use seasonal fruit for best flavor and price', 'Add a squeeze of lime to prevent browning on apples/bananas'],
    health_benefits: ['No heavy corn syrup', 'No artificial sweeteners', 'No sulfites', 'Actual fresh fruit vitamins and fiber', 'No BPA from metal cans'],
    vs_store_bought: 'Del Monte Fruit Cups in "heavy syrup" add sugar and corn syrup. "Light" versions use sucralose. Dole cups have ascorbic acid and citric acid. These are just real, fresh fruit in juice.',
    kid_friendly: true,
    allergens: [],
    dietary_tags: ['vegan', 'gluten-free', 'no-added-sugar']
  },

  // ── DESSERTS & SWEETS ──
  {
    name: 'Banana Nice Cream',
    description: 'Creamy soft-serve from frozen bananas — no dairy, no sugar, no cream',
    replaces_category: 'Ice Cream',
    replaces_products: [],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    total_time_minutes: 5,
    servings: 2,
    difficulty: 'easy',
    estimated_cost: 1.50,
    cost_per_serving: 0.75,
    ingredients: [
      { item: 'Frozen ripe bananas', amount: '3 large', notes: 'Peel, break into chunks, freeze overnight' },
      { item: 'Peanut butter', amount: '1 tbsp', notes: 'Optional — adds creaminess' },
      { item: 'Cocoa powder', amount: '1 tbsp', notes: 'Optional — for chocolate version' },
      { item: 'Splash of milk', amount: '1-2 tbsp', notes: 'Any kind — helps blending' }
    ],
    instructions: [
      'Add frozen banana chunks to food processor or powerful blender.',
      'Process, stopping to scrape sides. It will go through stages: crumbly → chunky → smooth.',
      'Add peanut butter and/or cocoa if using.',
      'Add splash of milk only if needed to get blending.',
      'Serve immediately for soft-serve texture.',
      'For scoopable texture: freeze 30-60 minutes.'
    ],
    tips: ['The riper the banana when frozen, the sweeter the result', 'Top with crushed nuts, coconut flakes, or mini chocolate chips'],
    health_benefits: ['No guar gum', 'No carrageenan', 'No mono and diglycerides', 'No polysorbate 80', 'No artificial flavors', 'Potassium from bananas'],
    vs_store_bought: 'Breyers contains corn syrup, mono and diglycerides, guar gum, carrageenan, polysorbate 80, and "natural flavor." Ben & Jerry\'s has similar additives. This is literally just frozen fruit.',
    kid_friendly: true,
    allergens: ['peanuts'],
    dietary_tags: ['vegan', 'gluten-free', 'no-added-sugar', 'dairy-free']
  },
  {
    name: 'Oat Flour Chocolate Chip Cookies',
    description: 'Chewy cookies with oat flour and dark chocolate — no bleached flour or artificial vanilla',
    replaces_category: 'Packaged Cookies',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 11,
    total_time_minutes: 21,
    servings: 24,
    difficulty: 'easy',
    estimated_cost: 6.00,
    cost_per_serving: 0.25,
    ingredients: [
      { item: 'Rolled oats', amount: '2.5 cups', notes: 'Blended into flour' },
      { item: 'Butter', amount: '1/2 cup', notes: 'Softened' },
      { item: 'Brown sugar', amount: '1/2 cup', notes: '' },
      { item: 'Egg', amount: '1 large', notes: '' },
      { item: 'Vanilla extract', amount: '1 tsp', notes: 'Real, not imitation' },
      { item: 'Dark chocolate chips', amount: '1 cup', notes: '60%+ cacao' },
      { item: 'Baking soda', amount: '1/2 tsp', notes: '' },
      { item: 'Salt', amount: '1/2 tsp', notes: '' }
    ],
    instructions: [
      'Blend oats in food processor until flour consistency (30 seconds).',
      'Cream butter and brown sugar until fluffy.',
      'Beat in egg and vanilla.',
      'Add oat flour, baking soda, and salt. Mix until just combined.',
      'Fold in chocolate chips.',
      'Scoop tablespoon-sized balls onto parchment-lined baking sheet.',
      'Bake at 350°F for 9-11 minutes — they\'ll look underdone (that\'s correct).',
      'Cool on sheet 5 minutes, then transfer to rack.'
    ],
    tips: ['Chill dough 30 minutes for thicker cookies', 'Freeze scooped dough balls — bake from frozen adding 2 minutes'],
    health_benefits: ['No TBHQ', 'No artificial vanilla (vanillin from wood pulp)', 'No enriched bleached flour', 'Whole grain fiber from oats', 'Real butter vs palm oil'],
    vs_store_bought: 'Chips Ahoy contains enriched flour, palm oil, TBHQ, artificial flavor, and soy lecithin. Oreos have palm oil, high fructose corn syrup, and vanillin. These use whole oats, real butter, and real vanilla.',
    kid_friendly: true,
    allergens: ['wheat', 'eggs', 'milk'],
    dietary_tags: ['whole-grain']
  },
  {
    name: 'Dark Chocolate Bark',
    description: 'Simple chocolate treat with nuts and fruit — no wax, no PGPR, no artificial flavors',
    replaces_category: 'Candy Bars',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 5,
    total_time_minutes: 75,
    servings: 12,
    difficulty: 'easy',
    estimated_cost: 6.00,
    cost_per_serving: 0.50,
    ingredients: [
      { item: 'Dark chocolate (70%+)', amount: '12 oz', notes: 'Bar or chips' },
      { item: 'Raw almonds', amount: '1/3 cup', notes: 'Roughly chopped' },
      { item: 'Dried cranberries', amount: '1/4 cup', notes: '' },
      { item: 'Pumpkin seeds', amount: '2 tbsp', notes: '' },
      { item: 'Flaky sea salt', amount: '1/2 tsp', notes: '' }
    ],
    instructions: [
      'Line a baking sheet with parchment paper.',
      'Melt chocolate: microwave in 30-second bursts, stirring between, until smooth.',
      'Pour onto parchment, spread to about 1/4 inch thick.',
      'Sprinkle toppings evenly over chocolate, press gently.',
      'Sprinkle with flaky salt.',
      'Refrigerate 1 hour until set.',
      'Break into irregular pieces. Store in cool place or fridge.'
    ],
    tips: ['Add espresso powder for mocha bark', 'Use white chocolate drizzle for visual appeal'],
    health_benefits: ['No PGPR (polyglycerol polyricinoleate)', 'No vanillin', 'No soy lecithin', 'Dark chocolate flavonoids (antioxidants)', 'No palm oil'],
    vs_store_bought: 'Hershey\'s contains sugar, milk, cocoa butter, soy lecithin, PGPR, and artificial flavor — with less than 30% actual cacao. Snickers adds TBHQ, corn syrup, and partially hydrogenated oil. Quality dark chocolate + whole toppings is a world apart.',
    kid_friendly: true,
    allergens: ['tree nuts'],
    dietary_tags: ['gluten-free', 'vegan']
  },

  // ── MORE STAPLES ──
  {
    name: 'Hummus From Scratch',
    description: 'Ultra-smooth hummus that puts Sabra to shame — no potassium sorbate, no citric acid',
    replaces_category: 'Hummus',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    total_time_minutes: 10,
    servings: 8,
    difficulty: 'easy',
    estimated_cost: 3.00,
    cost_per_serving: 0.38,
    ingredients: [
      { item: 'Canned chickpeas', amount: '15 oz can', notes: 'Reserve liquid (aquafaba)' },
      { item: 'Tahini', amount: '1/4 cup', notes: 'Stir well before measuring' },
      { item: 'Lemon juice', amount: '3 tbsp', notes: 'Fresh' },
      { item: 'Garlic', amount: '1 clove', notes: '' },
      { item: 'Olive oil', amount: '2 tbsp', notes: 'Plus extra for drizzling' },
      { item: 'Salt', amount: '1/2 tsp', notes: '' },
      { item: 'Ice water', amount: '2-3 tbsp', notes: 'The secret to smooth texture' },
      { item: 'Cumin', amount: '1/2 tsp', notes: 'Optional' }
    ],
    instructions: [
      'Drain chickpeas (save liquid). Optional: rub off skins for extra smooth.',
      'Process tahini and lemon juice for 1 minute until fluffy.',
      'Add garlic, salt, cumin. Process 30 seconds.',
      'Add chickpeas, process 1 minute.',
      'Drizzle in olive oil and ice water while processing.',
      'Run processor a full 3-4 minutes until silky smooth.',
      'Serve with olive oil drizzle and paprika. Keeps 5 days refrigerated.'
    ],
    tips: ['The secret is blending the tahini first, and running the processor much longer than you think', 'Remove chickpea skins for restaurant-quality smooth'],
    health_benefits: ['No potassium sorbate', 'No sodium benzoate', 'No soybean oil', 'No citric acid (irritant for some)', 'Heart-healthy chickpea fiber and olive oil'],
    vs_store_bought: 'Sabra hummus contains soybean oil (not olive oil), potassium sorbate, sodium benzoate, and citric acid. This uses real olive oil, fresh lemon, and no preservatives.',
    kid_friendly: true,
    allergens: ['sesame'],
    dietary_tags: ['vegan', 'gluten-free', 'high-fiber']
  },
  {
    name: 'Homemade Applesauce',
    description: 'Chunky or smooth applesauce with no added sugar — just apples and cinnamon',
    replaces_category: 'Applesauce',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    total_time_minutes: 30,
    servings: 6,
    difficulty: 'easy',
    estimated_cost: 4.00,
    cost_per_serving: 0.67,
    ingredients: [
      { item: 'Apples', amount: '6 medium', notes: 'Fuji, Gala, or Honeycrisp — sweeter varieties need less sugar' },
      { item: 'Water', amount: '1/2 cup', notes: '' },
      { item: 'Cinnamon', amount: '1 tsp', notes: '' },
      { item: 'Lemon juice', amount: '1 tbsp', notes: 'Prevents browning' }
    ],
    instructions: [
      'Peel, core, and chop apples into 1-inch chunks.',
      'Place in pot with water and lemon juice.',
      'Cover and cook over medium heat 15-20 minutes until very soft.',
      'Mash with fork for chunky, or blend for smooth.',
      'Stir in cinnamon.',
      'Serve warm or cold. Refrigerate up to 10 days, or freeze in portions.'
    ],
    tips: ['Mix apple varieties for complex flavor', 'Freeze in ice cube trays for baby food portions'],
    health_benefits: ['No added sugar', 'No high fructose corn syrup', 'No ascorbic acid', 'Natural fiber from whole apples', 'No preservatives'],
    vs_store_bought: 'Mott\'s adds high fructose corn syrup and ascorbic acid. Even "no sugar added" versions use water and ascorbic acid, losing flavor. Tree Top uses corn syrup. This is just real apples with cinnamon.',
    kid_friendly: true,
    allergens: [],
    dietary_tags: ['vegan', 'gluten-free', 'no-added-sugar']
  },
  {
    name: 'Nut-Free Sunflower Seed Butter',
    description: 'Creamy spread for school lunches where peanut butter is banned',
    replaces_category: 'Nut Butter Alternatives',
    replaces_products: [],
    prep_time_minutes: 5,
    cook_time_minutes: 10,
    total_time_minutes: 25,
    servings: 16,
    difficulty: 'easy',
    estimated_cost: 4.00,
    cost_per_serving: 0.25,
    ingredients: [
      { item: 'Raw sunflower seeds', amount: '2 cups', notes: 'Hulled' },
      { item: 'Coconut oil', amount: '1 tbsp', notes: 'Melted — helps blending' },
      { item: 'Honey', amount: '1 tbsp', notes: 'Optional' },
      { item: 'Salt', amount: '1/4 tsp', notes: '' }
    ],
    instructions: [
      'Toast sunflower seeds in oven at 325°F for 8-10 minutes until lightly golden.',
      'Cool slightly, then add to food processor.',
      'Process for 10-15 minutes total, scraping sides every 2-3 minutes.',
      'It will go: powder → clumpy ball → smooth butter. Be patient.',
      'Add coconut oil, honey, and salt in the last minute.',
      'Transfer to jar. Keeps 2 weeks at room temp, 1 month refrigerated.'
    ],
    tips: ['Patience is key — it WILL get smooth, just keep processing', 'Add cocoa powder for chocolate sunbutter'],
    health_benefits: ['No palm oil', 'No sugar (unless you add honey)', 'No mono and diglycerides', 'Rich in vitamin E and magnesium', 'Allergy-safe for schools'],
    vs_store_bought: 'SunButter contains sugar, palm oil, and mono and diglycerides. Store brands often add hydrogenated oils. This has 2-4 ingredients, all recognizable.',
    kid_friendly: true,
    allergens: [],
    dietary_tags: ['nut-free', 'gluten-free', 'vegan', 'school-safe']
  },
  {
    name: 'Sheet Pan Chicken Tenders',
    description: 'Crispy oven-baked chicken strips with panko coating — no sodium phosphates, no TBHQ',
    replaces_category: 'Frozen Chicken Tenders',
    replaces_products: [],
    prep_time_minutes: 15,
    cook_time_minutes: 18,
    total_time_minutes: 33,
    servings: 4,
    difficulty: 'easy',
    estimated_cost: 7.00,
    cost_per_serving: 1.75,
    ingredients: [
      { item: 'Chicken breast', amount: '1 lb', notes: 'Cut into strips' },
      { item: 'Panko breadcrumbs', amount: '1 cup', notes: '' },
      { item: 'Parmesan cheese', amount: '1/4 cup', notes: 'Finely grated' },
      { item: 'Egg', amount: '1 large', notes: 'Beaten' },
      { item: 'Flour', amount: '1/3 cup', notes: 'For dredging' },
      { item: 'Garlic powder', amount: '1 tsp', notes: '' },
      { item: 'Paprika', amount: '1 tsp', notes: '' },
      { item: 'Salt and pepper', amount: 'To taste', notes: '' },
      { item: 'Olive oil spray', amount: 'Light coating', notes: '' }
    ],
    instructions: [
      'Preheat oven to 425°F. Line baking sheet with parchment, lightly oil.',
      'Set up 3 bowls: flour + salt + pepper, beaten egg, panko + parmesan + garlic + paprika.',
      'Dredge each chicken strip: flour → egg → panko mixture.',
      'Place on baking sheet. Spray tops lightly with olive oil.',
      'Bake 8 minutes, flip, bake 8-10 more minutes until golden and 165°F internal.',
      'Let rest 3 minutes.'
    ],
    tips: ['Freeze breaded but unbaked strips on a sheet, then bag them — bake from frozen at 400°F for 25 minutes', 'A wire rack on the baking sheet = crispier bottoms'],
    health_benefits: ['No sodium phosphates', 'No TBHQ', 'No "mechanically separated chicken"', 'No bleached wheat flour', 'Real chicken breast, not reformed meat'],
    vs_store_bought: 'Tyson chicken tenders contain sodium phosphates, modified food starch, dextrose, bleached wheat flour, and soybean oil. Perdue adds TBHQ. Foster Farms contains "chicken breast with rib meat, water, seasoning." These are 100% real chicken breast.',
    kid_friendly: true,
    allergens: ['wheat', 'eggs', 'milk'],
    dietary_tags: ['high-protein']
  },
  {
    name: 'Instant Pot Bone Broth',
    description: 'Rich, gelatinous bone broth in 2 hours — replaces bouillon cubes and boxed broth',
    replaces_category: 'Broth & Bouillon',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 120,
    total_time_minutes: 150,
    servings: 10,
    difficulty: 'easy',
    estimated_cost: 5.00,
    cost_per_serving: 0.50,
    ingredients: [
      { item: 'Chicken carcass or beef bones', amount: '2-3 lbs', notes: 'Save bones from roast chicken' },
      { item: 'Water', amount: 'Enough to cover', notes: 'About 10 cups' },
      { item: 'Apple cider vinegar', amount: '2 tbsp', notes: 'Helps extract minerals from bones' },
      { item: 'Onion', amount: '1 large', notes: 'Quartered, skin on' },
      { item: 'Carrots', amount: '2', notes: 'Rough chop' },
      { item: 'Celery', amount: '2 stalks', notes: 'Rough chop' },
      { item: 'Garlic', amount: '4 cloves', notes: 'Smashed' },
      { item: 'Bay leaf', amount: '2', notes: '' },
      { item: 'Salt', amount: '1 tsp', notes: 'Add more after cooking to taste' },
      { item: 'Peppercorns', amount: '1 tsp', notes: '' }
    ],
    instructions: [
      'Add bones to Instant Pot. Cover with water, add vinegar.',
      'Add all vegetables and seasonings.',
      'Lock lid, set to Pressure Cook/Manual HIGH for 120 minutes.',
      'Natural release (about 20 minutes).',
      'Strain through fine mesh strainer. Discard solids.',
      'Season with salt to taste.',
      'Cool, then refrigerate. Fat will solidify on top — skim off or leave for richness.',
      'Freeze in 2-cup portions for up to 6 months.'
    ],
    tips: ['Good broth jiggles like Jello when cold — that\'s the collagen', 'Freeze in ice cube trays for small portions to add to rice, sauces, etc.'],
    health_benefits: ['No MSG', 'No autolyzed yeast extract', 'No "natural flavors"', 'Collagen and minerals from bones', 'No caramel color', 'No maltodextrin'],
    vs_store_bought: 'Knorr bouillon cubes contain MSG, palm oil, caramel color, maltodextrin, and "natural flavor." Swanson broth uses autolyzed yeast extract (hidden MSG). Pacific Foods uses "natural flavor." Homemade has real collagen and minerals.',
    kid_friendly: true,
    allergens: [],
    dietary_tags: ['gluten-free', 'dairy-free', 'paleo', 'high-protein']
  },
  {
    name: 'Frozen Yogurt Bark',
    description: 'Frozen snack that breaks apart like candy — real yogurt, real fruit, zero junk',
    replaces_category: 'Frozen Snacks',
    replaces_products: [],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    total_time_minutes: 130,
    servings: 8,
    difficulty: 'easy',
    estimated_cost: 4.00,
    cost_per_serving: 0.50,
    ingredients: [
      { item: 'Greek yogurt', amount: '2 cups', notes: 'Plain or vanilla' },
      { item: 'Honey', amount: '2 tbsp', notes: '' },
      { item: 'Fresh berries', amount: '1 cup', notes: 'Sliced strawberries, blueberries, raspberries' },
      { item: 'Granola', amount: '1/4 cup', notes: 'Your favorite' },
      { item: 'Mini chocolate chips', amount: '2 tbsp', notes: 'Optional' },
      { item: 'Coconut flakes', amount: '2 tbsp', notes: 'Optional' }
    ],
    instructions: [
      'Line a baking sheet with parchment paper.',
      'Mix yogurt with honey and spread evenly, about 1/4 inch thick.',
      'Scatter berries, granola, chocolate chips, and coconut on top.',
      'Gently press toppings into yogurt.',
      'Freeze at least 2 hours until solid.',
      'Break into irregular pieces. Store in freezer bag up to 1 month.'
    ],
    tips: ['Use seasonal fruit for best flavor', 'Drizzle with melted peanut butter before freezing for PB&J bark'],
    health_benefits: ['Live probiotics', 'Real fruit', 'No artificial colors or flavors', 'No guar gum or carrageenan', 'Protein from Greek yogurt'],
    vs_store_bought: 'Outshine bars contain corn syrup, guar gum, carob bean gum, and "natural flavor." Yasso bars add sugar, milk protein concentrate, and natural flavors. This is real yogurt with real fruit.',
    kid_friendly: true,
    allergens: ['milk'],
    dietary_tags: ['gluten-free', 'probiotic']
  },
  {
    name: 'Cauliflower Pizza Bites',
    description: 'Low-carb pizza bites that even kids love — replaces frozen pizza rolls and bagel bites',
    replaces_category: 'Pizza Rolls',
    replaces_products: [],
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    total_time_minutes: 35,
    servings: 6,
    difficulty: 'easy',
    estimated_cost: 5.00,
    cost_per_serving: 0.83,
    ingredients: [
      { item: 'Cauliflower', amount: '1 medium head', notes: 'Riced (or use frozen cauliflower rice)' },
      { item: 'Shredded mozzarella', amount: '1 cup', notes: '' },
      { item: 'Parmesan cheese', amount: '1/4 cup', notes: 'Grated' },
      { item: 'Egg', amount: '1 large', notes: '' },
      { item: 'Italian seasoning', amount: '1 tsp', notes: '' },
      { item: 'Garlic powder', amount: '1/2 tsp', notes: '' },
      { item: 'Pizza sauce', amount: '1/2 cup', notes: '' },
      { item: 'Mini pepperoni', amount: '1/4 cup', notes: 'Optional (look for uncured)' }
    ],
    instructions: [
      'Rice cauliflower in food processor. Microwave 4 minutes, let cool.',
      'Squeeze out ALL moisture using a towel — this is critical for crispy bites.',
      'Mix cauliflower, 1/2 cup mozzarella, parmesan, egg, Italian seasoning, garlic.',
      'Scoop tablespoon-sized mounds onto parchment-lined baking sheet.',
      'Flatten slightly into discs. Bake at 400°F for 15 minutes until golden.',
      'Add a dab of sauce, remaining mozzarella, and pepperoni.',
      'Bake 5 more minutes until cheese melts.',
      'Let cool 3 minutes (they crisp up).'
    ],
    tips: ['Squeeze the cauliflower DRY — seriously, as dry as possible', 'Freeze after first bake, add toppings when reheating'],
    health_benefits: ['No TBHQ', 'No BHA/BHT', 'No enriched flour', 'No sodium nitrite (if using uncured pepperoni)', 'Vegetable-based crust', 'Low carb'],
    vs_store_bought: 'Totino\'s Pizza Rolls contain enriched flour, BHA, BHT, TBHQ, soybean oil, modified food starch, sodium nitrite, and artificial flavor. Bagel Bites have similar. These are real vegetables with real cheese.',
    kid_friendly: true,
    allergens: ['eggs', 'milk'],
    dietary_tags: ['gluten-free', 'low-carb', 'keto']
  }
];

module.exports = additionalRecipes;
